### ISSUE TITLE
Devcontainer on Mac with Apple Silicon fails due to no AARCH64 support in Azure Functions Core Tools

### ISSUE THREAD

**Issue by MarkWme** [Azure/intro-to-intelligent-apps#12]
Running the dev container locally on a Mac with Apple Silicon will fail during the build of the container. The error will be similar to the following:

```
6.133 E: Unable to locate package azure-functions-core-tools
6.135 ERROR: Feature "Azure Functions Core Tools" (ghcr.io/
[2023-08-15T11:13:12.890Z] jlaundry/devcontainer-features/azure-functions-core-tools) failed to install! Look at the documentation at https://github.com/devcontainers/features/tree/main/src/azure-functions-core-tools for help troubleshooting this error.
```

This is because there is currently no official release of Azure Functions Core Tools that supports installation inside of a container when running on Apple Silicon:

Azure/azure-functions-core-tools#3112

**Comment by EverybodyKurts** [comment]
Almost 2 months later... is there any update? Thanks for any info.

**Comment by MarkWme** [comment]
I've saw that there is now official support for Azure Functions on Apple silicon, so I'm hoping this is now fixed. I will take a look over the next few days.

https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-on-apple-silicon-macs/

**Comment by MiguelElGallo** [comment]
Facing same issue.

**Comment by sebafo** [comment]
This is sadly not fixed. For the devcontainer we need a Linux AARCH64 version, but it is not available yet.
https://github.com/Azure/azure-functions-core-tools/issues/3112

**Comment by robinmanuelthiel** [comment]
When commenting out the Azure Function Tools in `.devcontainer/devcontainer.json`, the Dev Container starts in Apple Silicon.

```json
// "ghcr.io/jlaundry/devcontainer-features/azure-functions-core-tools:1": {
//     "version": "latest"
// }
```

The question is: Do we need the function tools at all? I don't see the any Azure Functions stuff anymore in the repo. @MarkWme can't we just remove this?

**Comment by MarkWme** [comment]
I have been thinking the same. I'm planning to review the whole repo again in the next week or so, so I'll take a look at this then and see if we can just remove this now.
