### ISSUE TITLE
Rename "Azure Cognitive Search" to "Azure AI Search". 

### ISSUE THREAD

**Issue by wrijughosh** [Azure/intro-to-intelligent-apps#61]
There are few places, but in labs/03-orchestration/README.md we need to rename it.

**Comment by denniszielke** [comment]
done

**Comment by jgarplind** [comment]
I think you forgot a couple of places under 04 Python.

Caused some confusion for us.

**Comment by denniszielke** [comment]
Ok we will take a look, but we will also gladly accept a PR ;-)

**Comment by jgarplind** [comment]
Was just helping a friend, but I might spend some time going through the lab myself - if so I'll send a PR to correct as I see fit :)

**Comment by MarkWme** [comment]
I think all references to Cognitive Search are gone now.
